
services:
  backend:
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    ports:
      - "5253:5253"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5253

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
