
services:
  backend:
    build:
      context: ./WebAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    # environment:
    #   - MONGO_URI=mongodb://mongo:27017

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8080

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
