name: Deploy .NET API
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push .NET Docker Image
        working-directory: Client_WebAPI/WebAPI
        run: |
          docker build -t ghcr.io/${{ github.actor }}/dotnet-api:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.actor }}/dotnet-api:latest