name: CI - .NET

on:
  push:
    branches:
      - main
      - cicd
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'

      - name: Restore Dependencies
        working-directory: Client_WebAPI/WebAPI
        run: dotnet restore 

      - name: Build Project
        working-directory: Client_WebAPI/WebAPI
        run: dotnet build

      - name: Run Tests
        working-directory: Client_WebAPI/WebAPI
        run: dotnet test --no-build --verbosity normal
